### ISSUE TITLE
Routing Login -> Sign-up -> Chatroom

### ISSUE THREAD

**Issue by simondarius** [MoldovanLorenzo/chatroorc#2]
Pagina default sa fie aia de home. Cand user-u apasa butonu de login faci un http request la 'http:localhost/5000/login_request ' (deocamndata) cu un fisier json de tipu {
  "username": "test1",
  "password": "test21"
}. Backendu raspunde "SUCCESS" daca loginu o avut success sau o erroare. Pentru sign-up la fel numa ca request la  'http:localhost/5000/signup_request ' . In functie de raspunsu la requesturi faci routingu, adica login->success->chatroom sau signup->success->login sau signup->erroare->afisezi eroare pe ecran etc....

**Comment by MoldovanLorenzo** [comment]
wazaaaaaaaa
